### ISSUE TITLE
Use .rds instead of .xlsx for clean data

### ISSUE THREAD

**Issue by nsbatra** [EPIET/IntroductoryCourse#3]
I recommend use of .rds instead of .xlsx for file format of exported clean data. This preserves the column classes when re-importing into R. 
This may also remove the need for the mutate_if() step, if those columns were previously classified as factors during data cleaning. For this step I would suggest across() anyway, because I think participants will be more confused about suddenly being exposed to a new (deprecated) function than seeing the across() syntax

**Comment by EKuki** [comment]
Done, thanks!
