### ISSUE TITLE
case_when errors 

### ISSUE THREAD

**Issue by nsbatra** [EPIET/IntroductoryCourse#4]
When I run this chunk in sequence following prior chunks (inject 9)

```
# Update incorrect ages to the correct values with case_when:  
linelist <- linelist %>%       
  mutate(age =                         
           case_when(                            
             # Where respondent is 16 and a teacher, change age to 61:
             age == 16 & group == "teacher" ~ 61,              
             # where respondent is 8 or 180 and a student, change age to 18:
             age == 8 & group == "student" ~ 18,              
             age == 180 & group == "student" ~ 18,              
             # Keep remaining values as is:              
             .default = as.numeric(age)              
             )                    
         ) 
```

This is producing this error for me:

```
Error in `mutate()`:
! Problem while computing `age = case_when(...)`.
Caused by error in `case_when()`:
! Case 4 (`age == 16 & group == "teacher" ~ 61`) must be a two-sided formula, not a double
  vector.
Backtrace:
 1. linelist %>% ...
 7. dplyr::case_when(...)
```

I think it is a problem with the last line using .default, since when it is hashed the problem goes away. Likely a class difference between as.numeric(ag) and the other integer values in other case_when rows.

It runs fine with this instead:

```
# Keep remaining values as is:              
             TRUE ~ age 
```

(which is how we taught it in the Applied Epi course

**Comment by AmyMikhail** [comment]
@nsbatra I just saw this and was curious - not sure how all the new injects / .qmd files fit together so I tested changing to `.default = ...` syntax for this chunk in the original Copenhagen case study and it works fine for me:

```r
# Update incorrect ages to the correct values with case_when:
linelist <- linelist %>% 
  
  mutate(age = 
           case_when(
             # If age 16 and a teacher, change their age to 61:
             age == 16 & group == "teacher" ~ 61, 
             # If age 8 or 180 and a student, change their age to 18:
             age %in% c(8, 180) & group == "student" ~ 18, 
             # Keep remaining values as is: 
             .default = as.numeric(age)
             )
         )
``` 

Note that the class of the age column before applying this step in the Copenhagen version is integer and the group variable has been converted from binary 0/1 to a labelled factor where teachers are 0 and students are 1 in the previous step.  I would check if maybe something is missing from that part in the inject?

**Comment by EKuki** [comment]
I see the same type of issue is reported here, with no clear resolution.
https://github.com/tidyverse/dplyr/issues/6810

I believe that since a recent 2023 update `case_when() `is prefered to be used with `.default`:
https://dplyr.tidyverse.org/reference/case_when.html

I have added a second line comment suggesting to use `TRUE ~ age` if `.default = as.numeric(age)` doesn't work.
