### ISSUE TITLE
Explicit argument names

### ISSUE THREAD

**Issue by nsbatra** [EPIET/IntroductoryCourse#5]
In the Applied Epi course we explicitly write out argument names whenever possible, to ease the learning of beginners who can get confused about which values are being used for which arguments. I would recommend this approach in this course too.

e.g. in inject 9

```
linelist <- linelist %>% 
  dplyr::mutate(
    # clinical symptoms
    across(c(diarrhoea, bloody, vomiting,
             abdo, nausea, fever,headache, jointpain), 
           ~as.logical(.)
           )
    )
```

You can write explicitly `.cols = ` and `.fns =` etc (or I think this syntax has just been updated... to whatever)

And for ggplot to, we dont just write `aes()` but instead write `mapping = aes()` which reminds the participants that this argument is for *mapping* columns to aesthetics

**Comment by EKuki** [comment]
Work in progress. Once I finish the last inject, I will review the whole code again to add any arguments missing.
thanks!
