### ISSUE TITLE
paste()

### ISSUE THREAD

**Issue by nsbatra** [EPIET/IntroductoryCourse#6]
Just so you know, we teach {stringr} so participants will have had brief exposure to str_glue() instead of paste() from base R.
I think it is fine/good to be aware of paste(), but just alerting you.
We find that for more involved combination of characters and objects that the str_glue() syntax is more understandable, and they have usually already loaded stringr e.g.
```
str_glue("There were {nrow(linelist)} cases in the outbreak as of {max(linelist$date, na.rm=T)}.)
```
or
```
str_glue("There were {a} cases in the outbreak as of {b}.,
      a = nrow(linelist),
      b = max(linelist$date, na.rm=T)
)
```

**Comment by EKuki** [comment]
Done, thanks!
